backend:
  name: github
  branch: master
  repo: https://github.com/houzhitaohzt/gatsby-learn.git

media_folder: static/assets

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}